- name: Get the grafana token(s)
  community.docker.docker_container_exec:
    container: influxdb
    command: influx auth find --json --org {{ influx_org }}
  register: token_result
  
# extract the token
- set_fact: 
    tokens: "{{ (token_result.stdout | from_json) }}"

- name: Delete every "grafana" token
  community.docker.docker_container_exec:
    container: influxdb
    command: influx auth delete -i {{ item.id }}
  loop: "{{ tokens }}"
  when: item.description == "grafana"
