- name: Delete the grafana and influxdb volumes
  community.docker.docker_volume:
    name: "{{ item }}"
    state: absent
  loop:
    - grafana_grafana_data
    - grafana_influx_config
    - grafana_influx_data

- name: Delete provisionning folder
  ansible.builtin.file:
    path: "{{ grafana_folder}}/dashboards"
    state: absent
