- name: Create the grafana folder
  ansible.builtin.file:
    path: "{{ grafana_folder }}"
    state: directory
    mode: '0755'

- name: Upload the compose file
  ansible.builtin.template:
    src: templates/compose.yaml.j2
    dest: "{{ grafana_folder }}/docker-compose.yaml"

- name: Start the compose file
  community.docker.docker_compose:
    project_src: "{{ grafana_folder }}"
  register: output
