- name: Stop the compose file
  community.docker.docker_compose:
    project_src: "{{ grafana_folder }}"
    state: absent

- name: Wait for the service to stop
  ansible.builtin.wait_for:
    timeout: 5
