---
- name: Install H2F station software
  hosts: station_servers

  tasks:
    - name: Setup the environment
      include_tasks: setup-env.yml
      tags:
        - install-all
        - setup-env
        
    - name: Stop previously installed services
      include_tasks: stop.yml
      tags:
        - fullclean
        - clean-grafana
        - clean-webui
        - clean-bridge

    - name: Clean previous install
      include_tasks: clean.yml
      tags:
        - fullclean
        - clean-grafana
        - clean-webui
        - clean-bridge

    - name: Install
      include_tasks: install.yml
      tags:
        - install-all
        - import-dashboards
        - install-grafana
        - install-webui
        - install-bridge
        - install-traefik
        - install-kiosk

    - name: Start
      include_tasks: start.yml
      tags:
        - install-all
        - install-grafana
        - install-webui
        - install-bridge
        - install-traefik
        - install-kiosk
