- name: Upload the kiosk service
  become: true
  ansible.builtin.template:
    src: templates/firefox-kiosk.service.j2
    dest: /etc/systemd/system/firefox-kiosk.service
- name: Upload the cage pam config
  become: true
  ansible.builtin.template:
    src: templates/cage.j2
    dest: /etc/pam.d/cage
- name: Reread configs (2.4 and above)
  become: true
  ansible.builtin.systemd_service:
    daemon_reload: true
- name: Enable the kiosk
  become: true
  ansible.builtin.service:
    name: firefox-kiosk
    enabled: true
