- name: Create temporary build directory
  ansible.builtin.tempfile:
    state: directory
    suffix: build
  register: builddir_res

# get the created dir
- set_fact: 
    builddir: "{{ builddir_res.path }}"

- name: Clone the main repo
  ansible.builtin.git:
    repo: "{{ H2F_control_repo }}"
    dest: "{{ builddir }}/webUI"
    version: main

- name: Upload the test entrypoint if we're in the test environment
  template:
    src: templates/set_iptable.sh.j2
    dest: "{{ builddir }}/test_entrypoint.sh"
    mode: '0774'
  when:
    webui_test_environment


- name: Upload the Dockefile
  ansible.builtin.template:
    src: templates/Dockerfile.j2
    dest: "{{ builddir }}/Dockerfile"

- name: Build the docker image (this can take some time >15min)
  community.docker.docker_image:
    name: webui
    build:
      path: "{{ builddir }}"
    source: build

- name: Create the webUI folder
  ansible.builtin.file:
    path: "{{ webui_folder }}"
    state: directory
    mode: '0755'

- name: Upload the compose file
  ansible.builtin.template:
    src: templates/compose.yaml.j2
    dest: "{{ webui_folder }}/docker-compose.yaml"
