FROM rust:1.81-alpine as builder
RUN apk add --no-cache musl-dev
COPY webUI webUI
WORKDIR webUI
RUN cargo install --path .

FROM alpine:3.20
COPY --from=builder /usr/local/cargo/bin/h2f_control /usr/local/bin/webUI
COPY webUI webUI
WORKDIR webUI

{% if webui_test_environment %}
COPY test_entrypoint.sh .
RUN apk add --no-cache iptables
CMD ["sh", "-c", "./test_entrypoint.sh"]
{% else %}
CMD ["webUI"]
{% endif %}
