- name: Create temporary build directory
  ansible.builtin.tempfile:
    state: directory
    suffix: build
  register: builddir_res

# get the created dir
- set_fact: 
    builddir: "{{ builddir_res.path }}"

# Use a plaintext deploy key, not great but it's only per-repo and read-only
- name: Copy over the deploy key
  ansible.builtin.copy:
    src: files/config_deploy_key
    dest: "{{ builddir }}/config_deploy_key"
    mode: '0600'

- name: Clone the main repo
  ansible.builtin.git:
    repo: https://github.com/lkzjdnb/industrial_bridge.git
    dest: "{{ builddir }}/industrial_bridge"


- name: Clone the config repo
  ansible.builtin.git:
    repo: git@github.com:lkzjdnb/bridge_config.git
    dest: "{{ builddir }}/config"
    key_file: "{{ builddir }}/config_deploy_key"
    accept_hostkey: yes

- name: Get an influxDB token
  community.docker.docker_container_exec:
    container: influxdb
    command: influx auth create --org {{ influx_org }} --write-buckets --json --description bridge
  register: token_result
  
# extract the token
- set_fact: 
    influxdb_token: "{{ (token_result.stdout | from_json).token }}"
    
- name: fetch config template from remote host
  fetch:
    src: "{{ builddir }}/config/config.yaml.j2"
    dest: /tmp/config.yaml.j2
    fail_on_missing : yes
    flat: yes

- name: reupload the templated config
  template:
    src: /tmp/config.yaml.j2
    dest: "{{ builddir }}/config/config.yaml"

- name: Upload the Dockefile
  ansible.builtin.template:
    src: templates/Dockerfile.j2
    dest: "{{ builddir }}/Dockerfile"

- name: Build the docker image (this can take some time >15min)
  community.docker.docker_image:
    name: industrial_bridge
    build:
      path: "{{ builddir }}"
    source: build

- name: Create the bridge folder
  ansible.builtin.file:
    path: "{{ bridge_folder }}"
    state: directory
    mode: '0755'

- name: Upload the compose file
  ansible.builtin.template:
    src: templates/compose.yaml.j2
    dest: "{{ bridge_folder }}/docker-compose.yaml"

- name: Start the compose file
  community.docker.docker_compose:
    project_src: "{{ bridge_folder }}"
  register: output
