- name: Create temporary build directory
  ansible.builtin.tempfile:
    state: directory
    suffix: build
  register: builddir_res

# get the created dir
- set_fact: 
    builddir: "{{ builddir_res.path }}"

- name: Clone the main repo
  ansible.builtin.git:
    repo: https://github.com/lkzjdnb/industrial_bridge.git
    dest: "{{ builddir }}/industrial_bridge"
    
- name: Upload the test entrypoint if we're in the test environment
  template:
    src: templates/set_iptable.sh.j2
    dest: "{{ builddir }}/test_entrypoint.sh"
    mode: '0774'
  when:
    bridge_test_environment

- name: Clone the config repo
  ansible.builtin.git:
    repo: https://github.com/lkzjdnb/bridge_config.git
    dest: "{{ builddir }}/config"

- name: Start the influxdb image for initial setup 
  community.docker.docker_container:
    name: influxdb
    state: started
    image: influxdb:2
    volumes:
      - grafana_influx_data:/var/lib/influxdb2
      - grafana_influx_config:/etc/influxdb2
    ports: 8086:8086

- name: Wait for influxdb to start
  ansible.builtin.wait_for:
    port: 8086
    delay: 5

- name: Get an influxDB token
  community.docker.docker_container_exec:
    container: influxdb
    command: influx auth create --org {{ influx_org }} --write-buckets --json --description bridge
  register: token_result

- name: Stop influxdb
  community.docker.docker_container:
    name: influxdb
    state: absent
  
# extract the token
- set_fact: 
    influxdb_token: "{{ (token_result.stdout | from_json).token }}"
    
- name: fetch config template from remote host
  fetch:
    src: "{{ builddir }}/config/config.yaml.j2"
    dest: /tmp/config.yaml.j2
    fail_on_missing : yes
    flat: yes

- name: reupload the templated config
  template:
    src: /tmp/config.yaml.j2
    dest: "{{ builddir }}/config/config.yaml"

- name: Upload the Dockefile
  ansible.builtin.template:
    src: templates/Dockerfile.j2
    dest: "{{ builddir }}/Dockerfile"

- name: Build the docker image (this can take some time >15min)
  community.docker.docker_image:
    name: industrial_bridge
    build:
      path: "{{ builddir }}"
    source: build

- name: Create the bridge folder
  ansible.builtin.file:
    path: "{{ bridge_folder }}"
    state: directory
    mode: '0755'

- name: Upload the compose file
  ansible.builtin.template:
    src: templates/compose.yaml.j2
    dest: "{{ bridge_folder }}/docker-compose.yaml"
