- name: Create temporary build directory
  ansible.builtin.tempfile:
    state: directory
    suffix: build
  register: builddir_res

# get the created dir
- set_fact: 
    builddir: "{{ builddir_res.path }}"

- name: Clone the main repo
  ansible.builtin.git:
    repo: "{{ H2F_control_deploy_repo }}"
    dest: "{{ builddir }}/setup"
    version: main

- name: Upload the Dockefile
  ansible.builtin.template:
    src: templates/Dockerfile.j2
    dest: "{{ builddir }}/Dockerfile"

- name: Build the docker image (this can take some time >15min)
  community.docker.docker_image:
    name: setup
    build:
      path: "{{ builddir }}"
    source: build

- name: Create the setup folder
  ansible.builtin.file:
    path: "{{ setup_folder }}"
    state: directory
    mode: '0755'

- name: Upload the compose file
  ansible.builtin.template:
    src: templates/compose.yaml.j2
    dest: "{{ setup_folder }}/docker-compose.yaml"
- name: Upload the script file
  ansible.builtin.template:
    src: templates/launch.sh
    dest: "{{ setup_folder }}/launch.sh"